TOKENS = [
    "if",
    "else",
    "(",
    ")",
    "{",
    "}",
    ";",
    "=",
    "+",
    "-",
    "*",
    "/",
    ">",
    "<",
    ">=",
    "<=",
    "==",
    "!=",
    "and",
    "or",
    "true",
    "false",
]

GRAMATICAS = {
    "t_id": [
        "S::=$A",
        "A::=aB|bB|cB|dB|eB|fB|gB|hB|iB|jB|kB|lB|mB|nB|oB|pB|qB|rB|sB|tB|uB|vB|wB|xB|yB|zB|wB|yB|zB",
        "B::=aB|bB|cB|dB|eB|fB|gB|hB|iB|jB|kB|lB|mB|nB|oB|pB|qB|rB|sB|tB|uB|vB|wB|xB|yB|zB|wB|yB|zB|_B|0B|1B|2B|3B|4B|5B|6B|7B|8B|9B|",
    ],
    "t_num": [
        "S::=1A|2A|3A|4A|5A|6A|7A|8A|9A|0A",
        "A::=1A|2A|3A|4A|5A|6A|7A|8A|9A|0A|",
    ],
}

SIMBOLO_INICIAL = "BLOCO_CODIGO"

NAO_TERMINAIS = [
    "BLOCO_CODIGO",
    "CODIGO_IF",
    "FINAL_CODIGO_IF",
    "BOOL",
    "OP_COMP",
    "VAL_COMP",
    "CODIGO",
    "SALVAR_VAR",
    "EQ",
    "OP",
    "VAL",
]

TERMINAIS = [
    "if",
    "else",
    "(",
    ")",
    "{",
    "}",
    "else",
    "true",
    "false",
    ">",
    "<",
    ">=",
    "<=",
    "==",
    "!=",
    "or",
    "and",
    "=",
    ";",
    "+",
    "-",
    "*",
    "/",
    "t_id",
    "t_num",
]

REGRAS_ESTATICAS = [
    "BLOCO_CODIGO ::= CODIGO",
    "BLOCO_CODIGO ::= CODIGO BLOCO_CODIGO",
    "CODIGO_IF ::= if ( BOOL ) { BLOCO_CODIGO } FINAL_CODIGO_IF",
    "FINAL_CODIGO_IF ::= else { BLOCO_CODIGO }",
    "FINAL_CODIGO_IF ::= if ( BOOL ) { BLOCO_CODIGO } FINAL_CODIGO_IF",
    "FINAL_CODIGO_IF ::= ε",
    "BOOL ::= VAL_COMP OP_COMP VAL_COMP",
    "BOOL ::= true",
    "BOOL ::= false",
    "OP_COMP ::= >",
    "OP_COMP ::= <",
    "OP_COMP ::= >=",
    "OP_COMP ::= <=",
    "OP_COMP ::= ==",
    "OP_COMP ::= !=",
    "OP_COMP ::= or",
    "OP_COMP ::= and",
    "VAL_COMP ::= ( BOOL )",
    "VAL_COMP ::= VAL",
    "CODIGO ::= SALVAR_VAR",
    "CODIGO ::= CODIGO_IF",
    "SALVAR_VAR ::= t_id = VAL EQ ;",
    "EQ ::= OP VAL EQ",
    "EQ ::= ε",
    "OP ::= +",
    "OP ::= -",
    "OP ::= *",
    "OP ::= /",
    "VAL ::= t_num",
]
