TOKENS = [
    "if",
    "(",
    ")",
    "{",
    "}",
    ";",
    "=",
    "+",
    "-",
    "*",
    "/",
    "&",
    ">",
    "<",
    ">=",
    "<=",
    "==",
    "!=",
    "and",
    "or",
    "true",
    "false",
]
GRAMATICAS = [
    ["S::=$A", "A::=a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|w|y|z"],
    ["S::=1A|2A|3A|4A|5A|6A|7A|8A|9A|0A", "A::=1A|2A|3A|4A|5A|6A|7A|8A|9A|0A|"],
]

SIMBOLO_INICIAL = "BLOCO_CODIGO"

NAO_TERMINAIS = [
    "BLOCO_CODIGO",
    "CODIGO_IF",
    "FINAL_CODIGO_IF",
    "BOOL",
    "OP_COMP",
    "VAL_COMP",
    "CODIGO",
    "SALVAR_VAR",
    "EQ",
    "OP",
    "VAL",
]

TERMINAIS = [
    "if",
    "(",
    ")",
    "{",
    "}",
    "else",
    "true",
    "false",
    ">",
    "<",
    ">=",
    "<=",
    "==",
    "!=",
    "or",
    "and",
    "t_id",
    "=",
    ";",
    "+",
    "-",
    "*",
    "/",
    "t_num",
]

REGRAS_ESTATICAS = [
    "BLOCO_CODIGO ::= CODIGO",
    "BLOCO_CODIGO ::= CODIGO BLOCO_CODIGO",
    "CODIGO_IF ::= if ( BOOL ) { BLOCO_CODIGO } FINAL_CODIGO_IF",
    "FINAL_CODIGO_IF ::= else { BLOCO_CODIGO }",
    "FINAL_CODIGO_IF ::= if ( BOOL ) { BLOCO_CODIGO } FINAL_CODIGO_IF",
    "FINAL_CODIGO_IF ::= ε",
    "BOOL ::= VAL_COMP OP_COMP VAL_COMP",
    "BOOL ::= true",
    "BOOL ::= false",
    "OP_COMP ::= >",
    "OP_COMP ::= <",
    "OP_COMP ::= >=",
    "OP_COMP ::= <=",
    "OP_COMP ::= ==",
    "OP_COMP ::= !=",
    "OP_COMP ::= or",
    "OP_COMP ::= and",
    "VAL_COMP ::= ( BOOL )",
    "VAL_COMP ::= VAL",
    "CODIGO ::= SALVAR_VAR",
    "CODIGO ::= CODIGO_IF",
    "SALVAR_VAR ::= t_id = VAL EQ ;",
    "EQ ::= OP VAL EQ",
    "EQ ::= ε",
    "OP ::= +",
    "OP ::= -",
    "OP ::= *",
    "OP ::= /",
    "VAL ::= t_num",
]
